package com.focuscoins.app;

import android.app.*; import android.content.*; import android.graphics.Color; import android.graphics.drawable.GradientDrawable; import android.os.*; import android.text.*; import android.view.*; import android.widget.*; import java.time.*;

public class CheckInActivity extends Activity {
 private Ledger ledger; private String pkg,app; private boolean limited; private LinearLayout box;
 @Override public void onCreate(Bundle b){super.onCreate(b);getWindow().setStatusBarColor(Color.rgb(239,248,246));ledger=new Ledger(this);pkg=getIntent().getStringExtra("pkg");app=getIntent().getStringExtra("app");limited=getIntent().getBooleanExtra("limited",false);showEntry();}
 private TextView text(String s,int sp,int color){TextView v=new TextView(this);v.setText(s);v.setTextSize(sp);v.setTextColor(color);v.setPadding(0,12,0,12);return v;} private EditText field(String hint,boolean number){EditText v=new EditText(this);v.setHint(hint);v.setInputType(number?android.text.InputType.TYPE_CLASS_NUMBER:android.text.InputType.TYPE_CLASS_TEXT|android.text.InputType.TYPE_TEXT_FLAG_CAP_SENTENCES);v.setPadding(24,18,24,18);GradientDrawable g=new GradientDrawable();g.setColor(Color.WHITE);g.setCornerRadius(24);v.setBackground(g);return v;} private Button primary(String s){Button b=new Button(this);b.setText(s);b.setTextColor(Color.WHITE);b.setTextSize(17);GradientDrawable g=new GradientDrawable(GradientDrawable.Orientation.LEFT_RIGHT,new int[]{Color.rgb(0,143,128),Color.rgb(0,116,105)});g.setCornerRadius(28);b.setBackground(g);return b;}
 private void showEntry(){ScrollView scroll=new ScrollView(this);box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);box.setPadding(56,92,56,56);box.setBackgroundColor(Color.rgb(239,248,246));scroll.addView(box);setContentView(scroll);box.addView(text("打开 "+(app==null?"应用":app),29,Color.rgb(13,42,40)));box.addView(text("写下目的和预计分钟，再开始使用",16,Color.rgb(91,117,112)));EditText purpose=field("这次打开要做什么？",false);purpose.setMinLines(2);box.addView(purpose);EditText duration=field("预计使用分钟数",true);box.addView(duration);TextView price=text("请输入预计分钟数",16,Color.rgb(0,116,105));box.addView(price);Runnable refresh=()->{int m=parseMinutes(duration);price.setText(m<1?"请输入预计分钟数":limited?"需投入 "+cost(m)+" 金币  ·  当前 "+ledger.coins():"免费使用  ·  当前 "+ledger.coins()+" 金币");};duration.addTextChangedListener(new TextWatcher(){public void beforeTextChanged(CharSequence s,int st,int c,int a){}public void onTextChanged(CharSequence s,int st,int b,int c){refresh.run();}public void afterTextChanged(Editable e){}});Button go=primary("开始使用");go.setOnClickListener(v->{String s=purpose.getText().toString().trim();int m=parseMinutes(duration);if(s.isEmpty()){purpose.setError("请先填写目的");return;}if(m<1){duration.setError("请输入 1–1440 分钟");return;}int charge=limited?cost(m):0;if(charge>0&&!ledger.spend(charge,app,m)){price.setText("金币不足，需要 "+charge+"，当前只有 "+ledger.coins());return;}if(charge==0)ledger.record("使用登记",app+" · "+m+" 分钟 · "+s+" · 免费");else ledger.record("使用目的",app+" · "+s);Intent service=new Intent(this,FocusService.class).setAction(FocusService.ACTION_SESSION).putExtra("pkg",pkg).putExtra("minutes",m);if(Build.VERSION.SDK_INT>=26)startForegroundService(service);else startService(service);Intent launch=getPackageManager().getLaunchIntentForPackage(pkg);if(launch!=null)startActivity(launch);finish();});box.addView(go);Button home=new Button(this);home.setText("取消并回到主屏幕");home.setTextColor(Color.rgb(0,116,105));home.setBackgroundColor(Color.TRANSPARENT);home.setOnClickListener(v->{startActivity(new Intent(Intent.ACTION_MAIN).addCategory(Intent.CATEGORY_HOME));finish();});box.addView(home);}
 private int parseMinutes(EditText input){try{int n=Integer.parseInt(input.getText().toString().trim());return n>=1&&n<=1440?n:-1;}catch(Exception e){return-1;}} private int cost(int minutes){int h=Instant.now().atZone(ZoneId.systemDefault()).getHour();return minutes*((h>=23||h<7)?Ledger.NIGHT_COST_PER_MIN:Ledger.COST_PER_MIN);} @Override public void onBackPressed(){startActivity(new Intent(Intent.ACTION_MAIN).addCategory(Intent.CATEGORY_HOME));finish();}
}
