package com.focuscoins.app;

import android.content.*; import org.json.*; import java.time.*;

public final class Ledger {
 private static final String PREF="focus_ledger",DATA="data"; private static final Object LOCK=new Object();
 public static final int EARN_PER_MIN=1,COST_PER_MIN=3,NIGHT_COST_PER_MIN=6,DAILY_START_COINS=30; private final Context context; private JSONObject root;
 public Ledger(Context c){context=c.getApplicationContext();synchronized(LOCK){load();settle(false);}}
 private static String dayKey(long ms){return Instant.ofEpochMilli(ms).atZone(ZoneId.systemDefault()).minusHours(7).toLocalDate().toString();}
 private void load(){try{root=new JSONObject(context.getSharedPreferences(PREF,0).getString(DATA,"{}"));}catch(Exception e){root=new JSONObject();}ensure();}
 private void ensure(){try{if(!root.has("day"))root.put("day",dayKey(System.currentTimeMillis()));if(!root.has("coins"))root.put("coins",DAILY_START_COINS);if(!root.has("debtTomorrow"))root.put("debtTomorrow",0);if(!root.has("rewards"))root.put("rewards",new JSONArray());if(!root.has("records"))root.put("records",new JSONArray());if(!root.has("daily"))root.put("daily",new JSONObject());if(!root.has("lastTick"))root.put("lastTick",System.currentTimeMillis());if(!root.has("screenRemainderMs"))root.put("screenRemainderMs",0);if(!root.has("awayRemainderMs"))root.put("awayRemainderMs",0);}catch(JSONException ignored){}}
 public void settleIfNeeded(){synchronized(LOCK){load();settle(false);}}
 private void settle(boolean alreadyDirty){try{String today=dayKey(System.currentTimeMillis());if(today.equals(root.getString("day"))){if(alreadyDirty)save();return;}String previousDay=root.getString("day");int coins=root.getInt("coins"),owed=root.getInt("debtTomorrow");JSONObject previous=root.getJSONObject("daily").optJSONObject(previousDay);long screenMs=previous==null?0:(previous.has("screenMs")?previous.optLong("screenMs"):previous.optInt("screenMinutes")*60_000L);int screenMinutes=(int)(screenMs/60_000L),roses=Math.max(0,coins);root.getJSONArray("rewards").put(new JSONObject().put("day",previousDay).put("coins",coins).put("roses",roses).put("screenMinutes",screenMinutes).put("item",reviewFor(screenMinutes)).put("notified",false));root.put("day",today).put("coins",DAILY_START_COINS-owed).put("debtTomorrow",0).put("lastTick",System.currentTimeMillis()).put("screenRemainderMs",0).put("awayRemainderMs",0);appendRecord("每日玫瑰",previousDay+" 剩余 "+coins+" 金币，收藏 🌹"+roses+" 朵");appendRecord("每日启动金币",DAILY_START_COINS+" 金币；偿还债务 "+owed+" 金币");save();}catch(JSONException ignored){}}
 private String reviewFor(int minutes){if(minutes<=60)return "🏆 手机昨天差点以为自己失宠了，克制力拉满！";if(minutes<=120)return "🌟 昨天两小时以内，手指和大脑都挺有分寸。";if(minutes<=240)return "🙂 昨天刷得有点热闹，不过还没把一天承包给屏幕。";if(minutes<=360)return "😅 手机昨天上班挺久，建议今天给它放个假。";if(minutes<=480)return "🫠 昨天拇指荣获劳动模范，眼睛正在申请加班费。";return "🚨 昨天手机陪伴超过 8 小时，眼睛已经递交调岗申请。";}
 public void tick(boolean screenOn,long now){synchronized(LOCK){load();settle(false);try{long last=root.getLong("lastTick"),elapsed=Math.max(0,Math.min(10*60_000L,now-last));if(elapsed==0)return;String key=screenOn?"screenRemainderMs":"awayRemainderMs";long accumulated=root.optLong(key)+elapsed,mins=accumulated/60_000L;root.put(key,accumulated%60_000L).put("lastTick",now);JSONObject all=root.getJSONObject("daily"),today=all.optJSONObject(dayKey(now));if(today==null){today=new JSONObject();all.put(dayKey(now),today);}String msKey=screenOn?"screenMs":"awayMs";long previous=today.has(msKey)?today.optLong(msKey):today.optInt(screenOn?"screenMinutes":"awayMinutes")*60_000L;today.put(msKey,previous+elapsed);if(!screenOn&&mins>0){ZonedDateTime z=Instant.ofEpochMilli(now).atZone(ZoneId.systemDefault());boolean night=z.getHour()>=23||z.getHour()<7;int delta=night?0:EARN_PER_MIN*(int)mins;root.put("coins",root.getInt("coins")+delta);today.put("earned",today.optInt("earned")+delta);}save();}catch(JSONException ignored){}}}
 public boolean spend(int amount,String app,int minutes){synchronized(LOCK){load();settle(false);try{int balance=root.getInt("coins");if(amount<0||balance<amount)return false;root.put("coins",balance-amount);JSONObject all=root.getJSONObject("daily"),today=all.optJSONObject(dayKey(System.currentTimeMillis()));if(today==null){today=new JSONObject();all.put(dayKey(System.currentTimeMillis()),today);}today.put("spent",today.optInt("spent")+amount);appendRecord("投入金币",app+" · "+minutes+" 分钟 · "+amount+" 金币");save();return true;}catch(Exception e){return false;}}}
 public boolean borrow(int amount){synchronized(LOCK){load();settle(false);try{JSONObject all=root.getJSONObject("daily"),today=all.optJSONObject(dayKey(System.currentTimeMillis()));if(today==null){today=new JSONObject();all.put(dayKey(System.currentTimeMillis()),today);}int count=today.has("borrowCount")?today.optInt("borrowCount"):Math.min(2,root.optInt("debtTomorrow")/30);if(count>=2)return false;today.put("borrowCount",count+1);root.put("coins",root.getInt("coins")+amount);root.put("debtTomorrow",root.getInt("debtTomorrow")+amount*2);appendRecord("借入",amount+" 金币到账；次日 07:00 偿还 "+amount*2+" 金币；今日已借 "+(count+1)+"/2 次");save();return true;}catch(Exception ignored){return false;}}}
 public int borrowCount(){synchronized(LOCK){load();settle(false);JSONObject all=root.optJSONObject("daily"),today=all==null?null:all.optJSONObject(dayKey(System.currentTimeMillis()));return today!=null&&today.has("borrowCount")?today.optInt("borrowCount"):Math.min(2,root.optInt("debtTomorrow")/30);}}
 public void record(String type,String text){synchronized(LOCK){load();try{appendRecord(type,text);save();}catch(Exception ignored){}}} private void appendRecord(String type,String text)throws JSONException{root.getJSONArray("records").put(new JSONObject().put("time",System.currentTimeMillis()).put("type",type).put("text",text));}
 public int coins(){synchronized(LOCK){load();return root.optInt("coins");}} public int debt(){synchronized(LOCK){load();return root.optInt("debtTomorrow");}}
 public JSONArray records(){synchronized(LOCK){load();return root.optJSONArray("records");}} public JSONArray rewards(){synchronized(LOCK){load();return root.optJSONArray("rewards");}} public JSONObject daily(){synchronized(LOCK){load();return root.optJSONObject("daily");}} public String currentDay(){synchronized(LOCK){load();return root.optString("day");}}
 public JSONObject pendingDailySummary(){synchronized(LOCK){load();JSONArray a=root.optJSONArray("rewards");if(a==null||a.length()==0)return null;JSONObject o=a.optJSONObject(a.length()-1);if(o==null||!o.has("screenMinutes")||o.optBoolean("notified",false))return null;try{return new JSONObject(o.toString());}catch(Exception e){return null;}}}
 public void markDailySummaryShown(String day){synchronized(LOCK){load();JSONArray a=root.optJSONArray("rewards");if(a==null)return;for(int i=a.length()-1;i>=0;i--){JSONObject o=a.optJSONObject(i);if(o!=null&&day.equals(o.optString("day"))){try{o.put("notified",true);save();}catch(Exception ignored){}return;}}}}
 public String exportJson(){synchronized(LOCK){load();return root.toString();}} public boolean importJson(String value){synchronized(LOCK){try{JSONObject n=new JSONObject(value);if(!n.has("records")||!n.has("rewards"))return false;root=n;ensure();save();return true;}catch(Exception e){return false;}}}
 private void save(){context.getSharedPreferences(PREF,0).edit().putString(DATA,root.toString()).commit();}
}
