package com.focuscoins.app;

import android.Manifest; import android.app.*; import android.app.admin.DevicePolicyManager; import android.content.*; import android.content.pm.*; import android.graphics.Color; import android.graphics.drawable.GradientDrawable; import android.net.Uri; import android.os.*; import android.provider.Settings; import android.view.*; import android.widget.*; import org.json.*; import java.text.*; import java.util.*;

public class MainActivity extends Activity {
 public static final String PREFS="focus_settings",CUSTOM_FREE="custom_free_apps",CUSTOM_LIMITED="custom_limited_apps"; private static final String AUTOSTART_CONFIRMED="autostart_confirmed",RECENTS_CONFIRMED="recents_confirmed"; private static final int IMPORT=20,EXPORT=21; private Ledger ledger; private LinearLayout box; private SharedPreferences prefs;
 @Override public void onCreate(Bundle b){super.onCreate(b);getWindow().setStatusBarColor(Color.rgb(239,248,246));getWindow().getDecorView().setSystemUiVisibility(View.SYSTEM_UI_FLAG_LIGHT_STATUS_BAR);ledger=new Ledger(this);prefs=getSharedPreferences(PREFS,0);requestBasics();}
 @Override protected void onResume(){super.onResume();if(ledger!=null){ledger=new Ledger(this);render();}}
 private int dp(int n){return(int)(n*getResources().getDisplayMetrics().density+.5f);} private TextView text(String s,int z,int c){TextView v=new TextView(this);v.setText(s);v.setTextSize(z);v.setTextColor(c);v.setPadding(0,dp(6),0,dp(6));return v;}
 private TextView title(String s){TextView v=text(s,19,Color.rgb(18,57,54));v.setTypeface(null,1);v.setPadding(0,dp(24),0,dp(10));return v;} private Button button(String s,View.OnClickListener l){Button b=new Button(this);b.setText(s);b.setTextColor(Color.rgb(0,116,105));b.setTextSize(15);b.setAllCaps(false);b.setOnClickListener(l);b.setMinHeight(dp(50));GradientDrawable g=new GradientDrawable();g.setColor(Color.rgb(231,247,243));g.setCornerRadius(dp(16));g.setStroke(dp(1),Color.rgb(201,230,223));b.setBackground(g);LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.setMargins(0,dp(5),0,dp(5));b.setLayoutParams(p);return b;}
 private LinearLayout card(){LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setPadding(dp(20),dp(18),dp(20),dp(18));GradientDrawable g=new GradientDrawable();g.setColor(Color.WHITE);g.setCornerRadius(dp(22));g.setStroke(dp(1),Color.rgb(226,237,234));c.setBackground(g);c.setElevation(dp(2));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.setMargins(0,0,0,dp(14));c.setLayoutParams(p);return c;}
 private void render(){ScrollView sc=new ScrollView(this);sc.setFillViewport(true);box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);box.setPadding(dp(22),dp(24),dp(22),dp(48));box.setBackgroundColor(Color.rgb(239,248,246));sc.addView(box);setContentView(sc);
  TextView hello=text("今日专注",32,Color.rgb(13,42,40));hello.setTypeface(null,1);box.addView(hello);box.addView(text(new SimpleDateFormat("M月d日 · EEEE",Locale.CHINA).format(new Date()),15,Color.rgb(91,117,112)));LinearLayout balance=card();GradientDrawable hero=new GradientDrawable(GradientDrawable.Orientation.TL_BR,new int[]{Color.rgb(219,244,238),Color.rgb(244,250,248)});hero.setCornerRadius(dp(24));balance.setBackground(hero);balance.addView(text("当前可用",14,Color.rgb(65,105,98)));TextView coin=text("🪙  "+ledger.coins(),46,Color.rgb(0,116,105));coin.setTypeface(null,1);balance.addView(coin);balance.addView(text("每天 07:00 发放 30 启动金币",15,Color.rgb(30,95,87)));balance.addView(text("受限应用日间每分钟 3 · 夜间每分钟 6 · 离屏每分钟 +1",13,Color.rgb(91,117,112)));if(ledger.debt()>0)balance.addView(text("明日待偿还 "+ledger.debt()+" 金币",14,Color.rgb(184,82,45)));box.addView(balance);
  box.addView(title("今日概览"));JSONObject today=ledger.daily().optJSONObject(ledger.currentDay());if(today==null)today=new JSONObject();long screenMs=today.has("screenMs")?today.optLong("screenMs"):today.optInt("screenMinutes")*60_000L,awayMs=today.has("awayMs")?today.optLong("awayMs"):today.optInt("awayMinutes")*60_000L;LinearLayout stats=card();stats.addView(text("使用屏幕  "+durationText(screenMs),18,Color.BLACK));stats.addView(text("离开屏幕  "+durationText(awayMs),18,Color.BLACK));stats.addView(text("获得 🪙 "+today.optInt("earned")+"  ·  消耗 🪙 "+today.optInt("spent"),15,Color.DKGRAY));box.addView(stats);
  box.addView(title("保护状态"));LinearLayout status=card();boolean running=FocusService.isRunning(this),overlay=Settings.canDrawOverlays(this),usage=hasUsageAccess(),admin=isAdmin(),battery=batteryUnrestricted(),accessibility=hasAccessibility();status.addView(text(running&&accessibility?"●  专注保护正在运行":"○  保护尚未完整开启",18,running&&accessibility?Color.rgb(0,137,117):Color.rgb(191,54,12)));status.addView(text("小米需要同时完成应用权限与系统后台保护。普通应用无法阻止系统强制停止。",14,Color.rgb(91,117,112)));if(!running)status.addView(button("启动保护服务",v->{FocusService.start(this);new Handler().postDelayed(this::render,500);}));if(!accessibility)status.addView(button("开启应用监听（必需）",v->startActivity(new Intent(Settings.ACTION_ACCESSIBILITY_SETTINGS))));if(!usage)status.addView(button("允许读取屏幕使用情况（备用）",v->startActivity(new Intent(Settings.ACTION_USAGE_ACCESS_SETTINGS))));if(!overlay)status.addView(button("允许显示提问与金币",v->enableOverlay()));if(!admin)status.addView(button("允许到时选择锁屏",v->enableAdmin()));box.addView(status);
  box.addView(title("手机后台保护"));LinearLayout keep=card();keep.addView(text("请完成下面 3 项。系统无法自动读取第 1、3 项，请设置后手动确认。",16,Color.rgb(18,57,54)));keep.addView(protectionCheck("已开启后台自启动",AUTOSTART_CONFIRMED,()->openAutostart()));keep.addView(button("2  电池策略设为无限制"+(battery?"  ✓":""),v->requestBatteryUnrestricted()));keep.addView(protectionCheck("已在最近任务中锁定",RECENTS_CONFIRMED,()->showRecentLockHelp()));box.addView(keep);
  box.addView(title("不可更改的规则"));LinearLayout fixed=card();fixed.addView(text("不受限应用：直接打开，不提问、不投入金币。",17,Color.BLACK));fixed.addView(text("不受限：电话、短信、通讯录、设置、系统界面/辅助功能、手机管家/安全、搜索、智能助理/语音助理、自带翻译/扫描、输入法、天气、健康、息屏/壁纸/背屏、笔记/备忘录、计算器、录音机、日历、时钟/闹钟、相机、文件管理、下载管理、高德地图、百度地图。",14,Color.DKGRAY));fixed.addView(text("受限：抖音/抖音极速版、快手/快手极速版、小红书、番茄系小说/七猫/起点、快看漫画/哔哩哔哩漫画、王者荣耀/和平精英/原神/元梦之星、斗鱼/虎牙、哔哩哔哩/腾讯视频/爱奇艺/优酷/芒果 TV/Netflix/YouTube、微博/知乎/贴吧/喜马拉雅/今日头条、淘宝/拼多多/得物/闲鱼。",14,Color.DKGRAY));fixed.addView(text("受限应用按预计时间预付；提前离开不退金币。到时可锁屏、回主屏幕或重新登记后继续。",14,Color.rgb(191,54,12)));box.addView(fixed);
  box.addView(title("其他应用"));LinearLayout rules=card();rules.addView(text("未列入固定名单的应用默认只提问、不扣金币；你可以将它们设为受限或明确设为免费。",14,Color.DKGRAY));rules.addView(button("自行设为受限  ·  "+validCustomSet(CUSTOM_LIMITED).size()+" 个",v->chooseApps(CUSTOM_LIMITED,"选择其他受限应用")));rules.addView(button("自行设为免费  ·  "+validCustomSet(CUSTOM_FREE).size()+" 个",v->chooseApps(CUSTOM_FREE,"选择其他免费应用")));box.addView(rules);
  box.addView(title("每日玫瑰与评语"));LinearLayout rewards=card();JSONArray rw=ledger.rewards();if(rw.length()==0)rewards.addView(text("还没有每日收藏。每天 07:00，剩余 1 金币兑换 1 朵红玫瑰，并根据屏幕使用时间生成评语。",14,Color.DKGRAY));for(int i=rw.length()-1;i>=0;i--){JSONObject o=rw.optJSONObject(i);String detail=o.has("screenMinutes")?"屏幕使用 "+durationText(o.optInt("screenMinutes")*60_000L):"旧版金币奖励";String roses=o.has("roses")?"  ·  🌹 "+o.optInt("roses")+" 朵":"";rewards.addView(text(o.optString("item")+"\n"+o.optString("day")+"  ·  "+detail+roses,16,Color.BLACK));}box.addView(rewards);
  box.addView(title("紧急借用"));LinearLayout borrow=card();int borrowed=ledger.borrowCount();borrow.addView(text("每日最多借 2 次，每次 15 金币，最多共 30。每借 15，次日 07:00 必须偿还 30。",15,Color.BLACK));borrow.addView(text("次日余额 = 30 启动金币 − 全部待偿还金额。今天借两次，次日扣清 60，新余额为 -30。",14,Color.rgb(184,82,45)));borrow.addView(button(borrowed>=2?"今日已借满 30 金币":"紧急借 15 金币  ·  剩余 "+(2-borrowed)+" 次",v->confirmBorrow()));box.addView(borrow);
  box.addView(title("最近活动"));LinearLayout records=card();JSONArray a=ledger.records();if(a.length()==0)records.addView(text("活动会显示在这里",14,Color.DKGRAY));for(int i=a.length()-1;i>=Math.max(0,a.length()-8);i--){JSONObject o=a.optJSONObject(i);if(o!=null)records.addView(text(o.optString("type")+"  ·  "+new SimpleDateFormat("MM-dd HH:mm",Locale.CHINA).format(new Date(o.optLong("time")))+"\n"+o.optString("text"),14,Color.DKGRAY));}box.addView(records);
  box.addView(title("数据"));LinearLayout data=card(),row=new LinearLayout(this);row.addView(button("导出",v->exportData()),new LinearLayout.LayoutParams(0,-2,1));row.addView(button("导入",v->importData()),new LinearLayout.LayoutParams(0,-2,1));data.addView(row);box.addView(data);
 }
 private String durationText(long ms){long minutes=Math.max(0,ms/60_000L);return minutes/60+" 小时 "+minutes%60+" 分钟";}
 private void chooseApps(String key,String heading){Intent x=new Intent(Intent.ACTION_MAIN).addCategory(Intent.CATEGORY_LAUNCHER);List<ResolveInfo> list=getPackageManager().queryIntentActivities(x,0);Collections.sort(list,new ResolveInfo.DisplayNameComparator(getPackageManager()));ArrayList<ResolveInfo> u=new ArrayList<>();HashSet<String>seen=new HashSet<>();for(ResolveInfo r:list){String pkg=r.activityInfo.packageName;if(seen.add(pkg)&&!pkg.equals(getPackageName())&&!FocusService.FIXED_FREE.contains(pkg)&&!FocusService.FIXED_LIMITED.contains(pkg))u.add(r);}String[] names=new String[u.size()];boolean[] checked=new boolean[u.size()];Set<String>cur=prefs.getStringSet(key,Collections.emptySet());for(int i=0;i<u.size();i++){names[i]=u.get(i).loadLabel(getPackageManager()).toString();checked[i]=cur.contains(u.get(i).activityInfo.packageName);}new AlertDialog.Builder(this).setTitle(heading).setMultiChoiceItems(names,checked,(d,which,isChecked)->checked[which]=isChecked).setNegativeButton("取消",null).setPositiveButton("完成",(d,w)->{Set<String>out=new HashSet<>();for(int i=0;i<checked.length;i++)if(checked[i])out.add(u.get(i).activityInfo.packageName);String other=key.equals(CUSTOM_LIMITED)?CUSTOM_FREE:CUSTOM_LIMITED;Set<String>opposite=new HashSet<>(prefs.getStringSet(other,Collections.emptySet()));opposite.removeAll(out);prefs.edit().putStringSet(key,new HashSet<>(out)).putStringSet(other,new HashSet<>(opposite)).apply();render();}).show();}
 private Set<String> validCustomSet(String key){Intent x=new Intent(Intent.ACTION_MAIN).addCategory(Intent.CATEGORY_LAUNCHER);Set<String>eligible=new HashSet<>();for(ResolveInfo r:getPackageManager().queryIntentActivities(x,0)){String pkg=r.activityInfo.packageName;if(!pkg.equals(getPackageName())&&!FocusService.FIXED_FREE.contains(pkg)&&!FocusService.FIXED_LIMITED.contains(pkg))eligible.add(pkg);}Set<String>result=new HashSet<>(prefs.getStringSet(key,Collections.emptySet()));result.retainAll(eligible);String other=key.equals(CUSTOM_FREE)?CUSTOM_LIMITED:CUSTOM_FREE;result.removeAll(prefs.getStringSet(other,Collections.emptySet()));return result;}
 private View protectionCheck(String label,String key,Runnable settings){LinearLayout row=new LinearLayout(this);row.setGravity(Gravity.CENTER_VERTICAL);CheckBox done=new CheckBox(this);done.setText(label);done.setTextSize(15);done.setChecked(prefs.getBoolean(key,false));done.setOnCheckedChangeListener((v,on)->prefs.edit().putBoolean(key,on).apply());row.addView(done,new LinearLayout.LayoutParams(0,-2,1));Button open=button("去设置",v->settings.run());row.addView(open,new LinearLayout.LayoutParams(dp(100),-2));return row;}
 private boolean hasUsageAccess(){AppOpsManager a=(AppOpsManager)getSystemService(APP_OPS_SERVICE);return a.checkOpNoThrow(AppOpsManager.OPSTR_GET_USAGE_STATS,android.os.Process.myUid(),getPackageName())==AppOpsManager.MODE_ALLOWED;} private boolean isAdmin(){return((DevicePolicyManager)getSystemService(DEVICE_POLICY_SERVICE)).isAdminActive(new ComponentName(this,FocusAdminReceiver.class));} private boolean hasAccessibility(){String enabled=Settings.Secure.getString(getContentResolver(),Settings.Secure.ENABLED_ACCESSIBILITY_SERVICES);return enabled!=null&&enabled.contains(getPackageName()+"/"+FocusAccessibilityService.class.getName());}
 private void requestBasics(){FocusService.start(this);if(Build.VERSION.SDK_INT>=33&&checkSelfPermission(Manifest.permission.POST_NOTIFICATIONS)!=PackageManager.PERMISSION_GRANTED)requestPermissions(new String[]{Manifest.permission.POST_NOTIFICATIONS},8);} private void confirmBorrow(){int count=ledger.borrowCount();if(count>=2){Toast.makeText(this,"今日已借满 30 金币，明日 07:00 扣清 60 金币",Toast.LENGTH_LONG).show();return;}new AlertDialog.Builder(this).setTitle("借用 15 金币？").setMessage("立即到账 15；明日 07:00 必须偿还 30。今日最多借两次，所有待还金额会一次扣清，余额可能变为负数。").setNegativeButton("取消",null).setPositiveButton("确认借用",(d,w)->{if(!ledger.borrow(15))Toast.makeText(this,"今日已达借用上限",Toast.LENGTH_LONG).show();render();}).show();}
 private void enableAdmin(){startActivity(new Intent(DevicePolicyManager.ACTION_ADD_DEVICE_ADMIN).putExtra(DevicePolicyManager.EXTRA_DEVICE_ADMIN,new ComponentName(this,FocusAdminReceiver.class)).putExtra(DevicePolicyManager.EXTRA_ADD_EXPLANATION,"仅在预计时间到后选择锁屏时使用"));} private void enableOverlay(){startActivity(new Intent(Settings.ACTION_MANAGE_OVERLAY_PERMISSION,Uri.parse("package:"+getPackageName())));}
 private boolean batteryUnrestricted(){return((PowerManager)getSystemService(POWER_SERVICE)).isIgnoringBatteryOptimizations(getPackageName());} private void requestBatteryUnrestricted(){try{startActivity(new Intent(Settings.ACTION_REQUEST_IGNORE_BATTERY_OPTIMIZATIONS,Uri.parse("package:"+getPackageName())));}catch(Exception e){startActivity(new Intent(Settings.ACTION_IGNORE_BATTERY_OPTIMIZATION_SETTINGS));}}
 private void openAutostart(){try{Intent i=new Intent();i.setComponent(new ComponentName("com.miui.securitycenter","com.miui.permcenter.autostart.AutoStartManagementActivity"));startActivity(i);}catch(Exception e){startActivity(new Intent(Settings.ACTION_APPLICATION_DETAILS_SETTINGS,Uri.parse("package:"+getPackageName())));}}
 private void showRecentLockHelp(){new AlertDialog.Builder(this).setTitle("锁定后台任务").setMessage("打开最近任务，长按“专注金币”卡片，点击锁形图标。完成后，即使清理其他后台任务，小米系统也会尽量保留专注保护。\n\n系统的“强制停止”和关闭无障碍权限仍然可以终止应用，这是 Android 保留给手机所有者的控制权。").setNegativeButton("知道了",null).setPositiveButton("打开最近任务",(d,w)->{if(!FocusAccessibilityService.showRecents())Toast.makeText(this,"请先开启应用监听，然后手动打开最近任务",Toast.LENGTH_LONG).show();}).show();}
 private void exportData(){startActivityForResult(new Intent(Intent.ACTION_CREATE_DOCUMENT).setType("application/json").putExtra(Intent.EXTRA_TITLE,"focus-coins-backup.json"),EXPORT);} private void importData(){startActivityForResult(new Intent(Intent.ACTION_OPEN_DOCUMENT).setType("application/json"),IMPORT);}
 @Override protected void onActivityResult(int r,int c,Intent d){super.onActivityResult(r,c,d);if(c!=RESULT_OK||d==null)return;try{Uri u=d.getData();if(r==EXPORT){try(java.io.OutputStream o=getContentResolver().openOutputStream(u)){o.write(ledger.exportJson().getBytes(java.nio.charset.StandardCharsets.UTF_8));}}else if(r==IMPORT){String s;try(java.io.InputStream in=getContentResolver().openInputStream(u);java.util.Scanner z=new java.util.Scanner(in,"UTF-8").useDelimiter("\\A")){s=z.hasNext()?z.next():"";}Toast.makeText(this,ledger.importJson(s)?"导入成功":"文件格式不正确",Toast.LENGTH_SHORT).show();render();}}catch(Exception e){Toast.makeText(this,"操作失败："+e.getMessage(),Toast.LENGTH_LONG).show();}}
}
